title: "Hao's Thoughts & Notes"
description: Notes and writing
author: hao
url: https://billhao.github.io

theme: minima
permalink: /:categories/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  date_format: "%Y-%m-%d"

header_pages:
  - tags.md
  - about.md

exclude:
  - drafts
  - README.md
  - .gitignore
